"""
Django settings for dcmc project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
import sys
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

sys.path.insert(0,os.path.join(BASE_DIR,'apps'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ocz$m+wc2q!bb(b_&^z3c4ox)850mz)w4-p9!%=l04ot_#q+lx'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'apps.pwd_app',
]

CORS_ORIGIN_ALLOW_ALL = True

CORS_ALLOW_METHODS = (
    'GET',
    'POST',
    'PUT',
    'PATCH',
    'DELETE',
    'OPTIONS'
)

CORS_ALLOW_HEADERS = (
    'x-requested-with',
    'content-type',
    'accept',
    'origin',
    'authorization',
    'x-csrftoken'
)

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'dcmc.RequestLogMiddleware.RequestLogMiddleware',
]

ROOT_URLCONF = 'dcmc.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dcmc.wsgi.application'

#配置文件目录
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, "media")


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'
TIME_ZONE = 'Asia/Shanghai'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


import os
path = os.path.split(os.path.realpath(__file__))[0]
log_path = os.path.join(path, '../logs/')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'api': {
            '()': 'dcmc.RequestLogMiddleware.RequestLogFilter',
        },
    },
    'formatters': {
        'info': {
            'format': '%(asctime)s - %(levelname)-8s - %(message)s'
        },
        'debug': {
            'format': '%(asctime)s - %(levelname)-8s - %(pathname)s [line:%(lineno)d] - %(message)s'
        },
        'api': {
            'format': '%(asctime)s - %(uri)s - %(source_ip)s - %(username)s - %(levelname)-8s - %(message)s'
        }
    },

    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'info',
        },
        'debug': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'formatter': 'debug',
            'filename': log_path + 'debug.log',
            'encoding': 'utf-8',
            'backupCount': 100,
            'maxBytes': 1024 * 1024 * 1,  # 1 MB
        },
        'main': {
            'level': 'INFO',
            'filters': ['api'],
            'formatter': 'api',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': log_path + 'main.log',
            'encoding': 'utf-8',
            'backupCount': 100,
            'when': 'D',
            'interval': 1,
            'delay': True,
        },
        'user': {
            'level': 'INFO',
            'filters': ['api'],
            'formatter': 'api',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': log_path + 'user.log',
            'encoding': 'utf-8',
            'backupCount': 100,
            'when': 'D',
            'interval': 1,
            'delay': True,
        },
        'ad':{
            'level': 'INFO',
            'filters': ['api'],
            'formatter': 'api',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': log_path + 'ad.log',
            'encoding': 'utf-8',
            'backupCount': 100,
            'when': 'D',
            'interval': 1,
            'delay': True,
        }
    },
    'loggers': {
        '': {
            'handlers': ['console', 'main'],
            'level': 'INFO',
            'propagate': False,
        },
        # 自定义模块日志
        'debug': {
            'handlers': ['debug'],
            'level': 'INFO',
            'propagate': False,
        },
        'user': {
            'handlers': ['user'],
            'level': 'INFO',
            'propagate': False,
        },
        'ad': {
            'handlers': ['ad'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}